avaresearch/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/respondents/login', 'Front\RespondentController@respondentLoginForm')->name('pageRespondentLogin');
Route::post('/respondents/login', 'Front\RespondentController@respondentLogin')->name('respondentLogin');
Route::get('/respondents/register', 'Front\RespondentController@index')->name('register_respondents');
//Demo Responends
Route::get('/respondents/registerdemo', 'Front\RespondentController@indexdemo')->name('register_respondents_demo');

Route::post('/suburb', 'Front\RespondentController@suburb')->name('suburb');
Route::post('/ethnicity', 'Front\RespondentController@ethnicity')->name('ethnicity');
Route::post('/add-respondent', 'Front\RespondentController@store')->name('add-respondent');

Route::get('/respondents/unsubscribe/{uuid}', 'Front\RespondentController@unsubscribe')->name('unsubscribeNow');

Route::post('/respondents/unsubscribe', 'Front\RespondentController@unsubscribeWithReason')->name('unsubscribe-respondent');

Route::get('/respondents/unsubscribeEmail/{uuid}', 'Front\RespondentController@emailUnsubscribe')->name('unsubscribeEmail');


//Route::post('/respondents/unsubscribe', 'Front\RespondentController@postUnsubscribe')->name('unsubscribe-respondent');

Route::post('/respondents/password/email', 'Auth\RespondentForgotPasswordController@sendResetLinkEmail')->name('respondent.password.email');
Route::get('/respondents/password/reset', 'Auth\RespondentForgotPasswordController@showLinkRequestForm')->name('respondent.password.request');
Route::post('/respondents/password/reset', 'Auth\RespondentResetPasswordController@reset')->name('respondent.password.update');
Route::get('/respondents/password/reset/{token}', 'Auth\RespondentResetPasswordController@showResetForm')->name('respondent.password.reset');

Route::get('/clients/login', 'Front\ClientController@login')->name('clientLogin');
Route::post('/clients/login', 'Front\ClientController@postLogin')->name('clientPostLogin');


Route::get('/', function () {
    return redirect(route('home'));
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile/edit', 'HomeController@editProfile')->name('edit-profile');
Route::post('/profile/edit', 'HomeController@saveProfile')->name('save-profile');

Route::get('/logout', function () {
    if (auth()->guard('respondent')->check()) {
        //auth('respondent')->user()->update(['login_status' => 0]);
        auth('respondent')->logout();
        return redirect(route('pageRespondentLogin'));
    } else if (auth()->check() && auth()->user()->type == 'client') {
        auth()->user()->update(['login_status' => 0]);
        auth()->logout();
        return redirect(route('clientLogin'));
    } else {
        if (auth()->check()) auth()->user()->update(['login_status' => 0]);
        auth()->logout();
        Session::flush();
        return redirect(route('login'));
    }
})->name('logout');

Route::group(['middleware' => 'auth'], function () {

    Route::resource('staffs', 'StaffController')->middleware('App\Http\Middleware\AdminMiddleware');

    //Clients
    Route::get('/clients/DTData', 'ClientController@DTData')->name('DTClients');
    Route::get('/clients/{uuid}/projects', 'ClientController@getProjects')->name('getProjects');
    Route::get('/clients/{uuid}/DTProjectData', 'ClientController@DTProjectData')->name('DTClientProjects');
    Route::resource('clients', 'ClientController');
    //----------

    //Email Templates
    Route::get('/email-templates/DTData', 'EmailTemplateController@DTData')->name('DTEmailTemplates');
    Route::delete('/email-templates/deleteEmailTempAttach', 'EmailTemplateController@deleteEmailTempAttach')->name('deleteEmailTempAttach');
    Route::get('/email-templates/{template}/json', 'EmailTemplateController@singleJson')->name('EmailTemplateSingleJson');
    Route::resource('email-templates', 'EmailTemplateController');
    //--------------------

    //SMS Templates
    Route::get('/sms-templates/DTData', 'SMSTemplateController@DTData')->name('DTSMSTemplates');
    Route::resource('sms-templates', 'SMSTemplateController');
    //--------------------

    //Calendar
    Route::get('/calendar/DTData', 'CalendarController@DTData')->name('DTCalendar');
    Route::resource('calendar', 'CalendarController');

    //Staff Qualified Report
    Route::post('/staff-qualified-report/getData', 'StaffReportController@getData')->name('getDataDTQualifiedReport');
    Route::resource('staff-qualified-report', 'StaffReportController');

    //Qulified Report
    //Route::resource('/reports', 'QulifiedReportController');

    //Leads
    Route::resource('leads', 'LeadController');

    
});

avaresearch/app/Models/SMSTemplate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class SMSTemplate extends Model
{
    use SoftDeletes;
    protected $guarded = ['uuid'];

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->uuid = (string) Str::uuid();
        });
    }

    public function createdBy()
    {
        return $this->belongsTo('App\User', 'created_by', 'id');
    }
}

avaresearch/app/Http/Controllers/SMSTemplateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\SMSTemplate;
use Yajra\Datatables\Datatables;

class SMSTemplateController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('sms_templates.index');
    }

    public function DTData()
    {
        $templates = SMSTemplate::select(
            'id',
            'uuid',
            'title',
            'isactive',
            'created_by',
            'created_at'
        );
        return Datatables::of($templates)
            ->addColumn('template_name', function ($template) {
                return '<a href="' . route('sms-templates.edit', $template->uuid) . '">
                    ' . $template->title  . '
                </a>';
            })
            ->addColumn('created_user_name', function ($template) {
                if ($template->createdBy != null) {
                    return '<a href="' . route('staffs.edit', $template->createdBy->uuid) . '">
                    ' . $template->createdBy->profile->first_name . ' ' . $template->createdBy->profile->last_name . '
                </a>';
                } else {
                    return '';
                }
            })
            ->editColumn('created_at', function ($template) {
                return $template->created_at->format('d-m-Y');
            })
            ->addColumn('actions', function ($template) {
                return '<td>
                <a href="' . route('sms-templates.edit', $template->uuid) . '"><i class="icon-pencil mr-3"></i></a>
                <a href="javascript:void(0);" class="delete_btn" data-id="' . $template->id . '" data-name="' . $template->title . '"><i class="icon-trash"></i></a>
            </td>';
            })->rawColumns(['template_name', 'actions', 'created_user_name'])->make(true);
    }

    public function create()
    {
        return view('sms_templates.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'title' => 'required|max:255',
            'message' => 'required'
        ];
        $this->validate($request, $rules, []);

        //dd($request->all());

        $data = $request->all();
        $data['created_by'] = auth()->id();

        $template = SMSTemplate::create($data);
        if ($template) {
            return redirect()->back()->withSuccess('SMS Template created successfully!');
        } else
            return redirect()->back()->withErrors(['message' => 'Problem while creating sms template. Please try again']);
    }

    public function edit($uuid)
    {
        $template = SMSTemplate::where('uuid', $uuid)->first();
        return view('sms_templates.edit', compact('template'));
    }

    public function update(Request $request, SMSTemplate $smsTemplate)
    {
        $rules = [
            'title' => 'required|max:255',
            'message' => 'required'
        ];

        $this->validate($request, $rules, []);

        $data = $request->all();
        $data['modified_by'] = auth()->id();

        $smsTemplate->update($data);

        return redirect()->back()->withSuccess('SMS Template updated successfully!');
    }

    public function destroy(SMSTemplate $smsTemplate)
    {
        $smsTemplate->delete();
        return response()->json(1);
    }
}

avaresearch/resources/views/sms_templates/create.blade.php
@extends('layouts.app')
@section('title', 'Create SMS Template')
@section('content')
<div class="container-fluid animatedParent animateOnce my-3 white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">
    <!-- <h4 class="">Fill up the details</h4> -->
    <a href="{{ route('sms-templates.index') }}" class="btn btn-secondary btn-xs"><i class="icon-arrow_back"></i> Back
      to
      List</a>
    <hr />
    @if(session('success'))
    <div class="toast" data-title="Success" data-message="{{ session("success") }}" data-type="success"></div>
    @endif

    @if ($errors->any())
    <div class="alert alert-danger">
      <ul class="mb-0">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif

    <form class="form-horizontal" action="{{ route('sms-templates.store') }}" method="POST"
      enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="title" class="control-label">Title <sup class="mandatory">*</sup></label>
            <input class="form-control" id="title" type="text" name="title" value="{{ old('title') }}" required />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="message" class="control-label">Message <sup class="mandatory">*</sup></label>
            <div class="clear-fix"></div>
            <blockquote class="text-primary">Maximum Number of characters for this text box is 152.</blockquote>
            <textarea name="message" id="message" rows="10" class="form-control" maxlength="152"
              required>{{ old('message') }}</textarea>
            <small>You have <b id="remain_char">144</b> characters remaining for your
              description...</small>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <button class="btn btn-primary"><i class="fa fa-save mr-2"></i>Submit</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

@section('footer')
<script>
  var maxLen = 152;
  function char_count_message(){
    var Length = $("#message").val().length;
    var AmountLeft = maxLen - Length;
    $('#remain_char').html(AmountLeft);
    if(Length >= maxLen){
      if (event.which != 8) {
          return false;
      }
    }
  }
  $('#message').keyup(function(){
    char_count_message();
  });
</script>
@endsection

avaresearch/resources/views/sms_templates/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit SMS Template :: '.$template->title)
@section('content')
<div class="container-fluid animatedParent animateOnce my-3 white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">
    <!-- <h4 class="">Fill up the details</h4> -->
    <a href="{{ route('sms-templates.index') }}" class="btn btn-secondary btn-xs"><i class="icon-arrow_back"></i> Back
      to
      List</a>
    <hr />
    @if(session('success'))
    <div class="toast" data-title="Success" data-message="{{ session("success") }}" data-type="success"></div>
    @endif

    @if ($errors->any())
    <div class="alert alert-danger">
      <ul class="mb-0">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif

    <form class="form-horizontal" action="{{ route('sms-templates.update', $template->id) }}" method="POST"
      enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="title" class="control-label">Title <sup class="mandatory">*</sup></label>
            <input class="form-control" id="title" type="text" name="title" value="{{ old('title', $template->title) }}"
              required />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="message" class="control-label">Message <sup class="mandatory">*</sup></label>
            <div class="clear-fix"></div>
            <blockquote class="text-primary">Maximum Number of characters for this text box is 152.</blockquote>
            <textarea name="message" id="message" rows="10" class="form-control" maxlength="152"
              required>{{ old('message', $template->message) }}</textarea>
            <small>You have <b id="remain_char">144</b> characters remaining for your
              description...</small>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <button class="btn btn-primary"><i class="fa fa-save mr-2"></i>Save Changes</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

@section('footer')
<script>
  $(document).ready(function(){
    char_count_message();
  });
  var maxLen = 152;
  function char_count_message(){
    var Length = $("#message").val().length;
    var AmountLeft = maxLen - Length;
    $('#remain_char').html(AmountLeft);
    if(Length >= maxLen){
      if (event.which != 8) {
          return false;
      }
    }
  }
  $('#message').keyup(function(){
    char_count_message();
  });
</script>
@endsection

avaresearch/resources/views/sms_templates/index.blade.php
@extends('layouts.app')
@section('title', 'SMS Templates')
@section('content')
<div class="container-fluid animatedParent animateOnce my-3 white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">
    <!-- <h4 class="">Registered Staffs</h4> -->
    <a href="{{ route('sms-templates.create') }}" class="btn btn-primary btn-xs"><i class="icon-plus"></i> Add New</a>
    <hr />
    @if(session('success'))
    <div class="alert alert-success">{{ session("success") }}</div>
    @endif
    <div class="table-responsive">
      <table class="table table-bordered table-hover" id="list_table">
        <thead>
          <tr>
            <th>Serial No</th>
            <th visible="hide">Title</th>
            <th>Title</th>
            <th>Created By</th>
            <th>Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <!-- Data will be placed here -->
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection
@section('footer')
<script>
  $(document).ready(function() {
      $("#list_table").DataTable({
        sDom: "Rlfrtip",
        processing: true,
        serverSide: true,
        pageLength: 10,
        ajax: "{{ route('DTSMSTemplates') }}",
        columns: [
          {
            "title": "Serial",
            render: function (data, type, row, meta) {
              return meta.row + meta.settings._iDisplayStart + 1;
            },
            width: '2%'
          },
          { data: 'title', name: 'title', visible: false },
          { data: 'template_name', name: 'title'},
          { data: 'created_user_name', name: 'created_by'},
          { data: 'created_at', name: 'created_at'},
          {
            data: "actions",
            name: "actions",
            orderable: false,
            searchable: false
          }
        ],
        order: [[0, "asc"]]
      });
    });
    $(document).on("click", ".delete_btn", function() {
      var id = $(this).data("id");
      var name = $(this).data("name");
      var row = $(this).closest("tr");
      swal(
        {
          title: "Are you sure to delete",
          text: "Name: " + name,
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-success",
          confirmButtonText: "Yes",
          cancelButtonText: "No",
          closeOnConfirm: false,
          showLoaderOnConfirm: true
        },
        function(isConfirm) {
          if (isConfirm) {
            $.ajax({
              url: "{{ route('sms-templates.index') }}/" + id,
              type: "DELETE",
              data: { _token: "{{ csrf_token() }}" },
              success: function(res) {
                if (res) {
                  row.remove();
                  swal("Deleted", "You deleted the template: " + name, "success");
                }
              },
              error: function(err) {
                console.log(err);
              }
            });
          }
        }
      );
    });
</script>
@endsection