avaresearch/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/respondents/login', 'Front\RespondentController@respondentLoginForm')->name('pageRespondentLogin');
Route::post('/respondents/login', 'Front\RespondentController@respondentLogin')->name('respondentLogin');
Route::get('/respondents/register', 'Front\RespondentController@index')->name('register_respondents');
//Demo Responends
Route::get('/respondents/registerdemo', 'Front\RespondentController@indexdemo')->name('register_respondents_demo');

Route::post('/suburb', 'Front\RespondentController@suburb')->name('suburb');
Route::post('/ethnicity', 'Front\RespondentController@ethnicity')->name('ethnicity');
Route::post('/add-respondent', 'Front\RespondentController@store')->name('add-respondent');

Route::get('/respondents/unsubscribe/{uuid}', 'Front\RespondentController@unsubscribe')->name('unsubscribeNow');

Route::post('/respondents/unsubscribe', 'Front\RespondentController@unsubscribeWithReason')->name('unsubscribe-respondent');

Route::get('/respondents/unsubscribeEmail/{uuid}', 'Front\RespondentController@emailUnsubscribe')->name('unsubscribeEmail');


//Route::post('/respondents/unsubscribe', 'Front\RespondentController@postUnsubscribe')->name('unsubscribe-respondent');

Route::post('/respondents/password/email', 'Auth\RespondentForgotPasswordController@sendResetLinkEmail')->name('respondent.password.email');
Route::get('/respondents/password/reset', 'Auth\RespondentForgotPasswordController@showLinkRequestForm')->name('respondent.password.request');
Route::post('/respondents/password/reset', 'Auth\RespondentResetPasswordController@reset')->name('respondent.password.update');
Route::get('/respondents/password/reset/{token}', 'Auth\RespondentResetPasswordController@showResetForm')->name('respondent.password.reset');

Route::get('/clients/login', 'Front\ClientController@login')->name('clientLogin');
Route::post('/clients/login', 'Front\ClientController@postLogin')->name('clientPostLogin');


Route::get('/', function () {
    return redirect(route('home'));
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile/edit', 'HomeController@editProfile')->name('edit-profile');
Route::post('/profile/edit', 'HomeController@saveProfile')->name('save-profile');

Route::get('/logout', function () {
    if (auth()->guard('respondent')->check()) {
        //auth('respondent')->user()->update(['login_status' => 0]);
        auth('respondent')->logout();
        return redirect(route('pageRespondentLogin'));
    } else if (auth()->check() && auth()->user()->type == 'client') {
        auth()->user()->update(['login_status' => 0]);
        auth()->logout();
        return redirect(route('clientLogin'));
    } else {
        if (auth()->check()) auth()->user()->update(['login_status' => 0]);
        auth()->logout();
        Session::flush();
        return redirect(route('login'));
    }
})->name('logout');

Route::group(['middleware' => 'auth'], function () {

    Route::resource('staffs', 'StaffController')->middleware('App\Http\Middleware\AdminMiddleware');

    //Clients
    Route::get('/clients/DTData', 'ClientController@DTData')->name('DTClients');
    Route::get('/clients/{uuid}/projects', 'ClientController@getProjects')->name('getProjects');
    Route::get('/clients/{uuid}/DTProjectData', 'ClientController@DTProjectData')->name('DTClientProjects');
    Route::resource('clients', 'ClientController');
    //----------

    //Email Templates
    Route::get('/email-templates/DTData', 'EmailTemplateController@DTData')->name('DTEmailTemplates');
    Route::delete('/email-templates/deleteEmailTempAttach', 'EmailTemplateController@deleteEmailTempAttach')->name('deleteEmailTempAttach');
    Route::get('/email-templates/{template}/json', 'EmailTemplateController@singleJson')->name('EmailTemplateSingleJson');
    Route::resource('email-templates', 'EmailTemplateController');
    //--------------------

    //SMS Templates
    Route::get('/sms-templates/DTData', 'SMSTemplateController@DTData')->name('DTSMSTemplates');
    Route::resource('sms-templates', 'SMSTemplateController');
    //--------------------

    //Calendar
    Route::get('/calendar/DTData', 'CalendarController@DTData')->name('DTCalendar');
    Route::resource('calendar', 'CalendarController');

    //Staff Qualified Report
    Route::post('/staff-qualified-report/getData', 'StaffReportController@getData')->name('getDataDTQualifiedReport');
    Route::resource('staff-qualified-report', 'StaffReportController');

    //Qulified Report
    //Route::resource('/reports', 'QulifiedReportController');

    //Leads
    Route::resource('leads', 'LeadController');

    
});

avaresearch/app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\User;
use App\UserDetail;
use Auth;
use Yajra\Datatables\Datatables;
use App\Models\Project;
use App\Rules\DomainOnly;

class ClientController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('clients.index');
    }

    public function DTData()
    {
        $clients = User::leftjoin('user_details', 'user_details.user_id', '=', 'users.id')
            ->select(
                'users.id',
                'users.uuid',
                'users.email',
                'users.isactive',
                'user_details.first_name',
                'user_details.last_name',
                'user_details.address',
                'user_details.contact_no',
                'users.created_by',
                'users.created_at'
            )->where('users.type', 'client');
        return Datatables::of($clients)
            ->addColumn('image', function ($client) {
                return '<div class="d-flex">
                <div class="avatar avatar-md mr-3 mb-2 mt-1">
                  <span
                    class="avatar-letter avatar-letter-' . strtolower(substr($client->profile->first_name, 0, 1)) . ' avatar-md circle"
                  ></span>
                </div>
                <div>
                    <div>
                    <a href="' . route('clients.edit', $client->uuid) . '">
                        <strong>' . $client->profile->first_name . ' ' . $client->profile->last_name . '</strong>
                    </a>
                    </div>
                    <small>' . $client->email . '</small>
                </div>
              </div>';
            })
            ->addColumn('created_user_name', function ($client) {
                if ($client->createdBy != null) {
                    return '<a href="' . route('staffs.edit', $client->createdBy->uuid) . '">
                    ' . $client->createdBy->profile->first_name . ' ' . $client->createdBy->profile->last_name . '
                </a>';
                } else {
                    return '';
                }
            })
            ->editColumn('created_at', function ($client) {
                return $client->created_at->format('d-m-Y');
            })
            ->addColumn('actions', function ($client) {
                return '<td>
                    <a href="' . route('clients.edit', $client->uuid) . '"><i class="icon-pencil mr-3"></i></a>
                    <a href="javascript:void(0);" class="delete_btn" data-id="' . $client->id . '" data-name="' . $client->profile->first_name . '"><i class="icon-trash"></i></a>
                </td>';
            })->rawColumns(['image', 'actions', 'created_user_name'])->make(true);
    }

    public function create()
    {
        return view('clients.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'first_name' => 'required|max:255',
            'last_name' => 'required|max:255',
            'company_name' => 'required|max:255',
            'contact_no' => 'required|numeric',
            'email' => 'required|unique:users|email|max:255',
            //'password' => 'required|min:5|max:10|confirmed',
            //'password_confirmation' => 'required|min:5|max:10',
            'address' => 'required'
        ];
        $this->validate($request, $rules, ['password.confirmed' => 'Password and Confirm Password not matched']);

        $args = $request->only(['email', 'password']);
        $args['type'] = 'client';
        if($args['password'] == null){
            $args['password'] = bcrypt("AVA@2020!");  
        }else{
            $args['password'] = bcrypt($request->password);
        }
        
        $username = explode('@', $request->email);
        $username = $username[0];
        $user = User::where('username', $username)->exists();
        if ($user) $username = $username . rand(1, 99);
        $args['username'] = $username;
        $args['created_by'] = auth()->id();

        $user = User::create($args);
        if ($user) {
            $args = $request->except(['email', 'password', 'password_confirmation']);
            $path = 'avatar-images/' . date('Y') . '/' . date('m');
            if ($request->file('image')) {
                $uploadedFile = $request->file('image');
                $filename = time() . $uploadedFile->getClientOriginalName();
                Storage::disk('public')->putFileAs($path, $uploadedFile, $filename);
                $args['image'] = $path . '/' . $filename;
            }


            $args['user_id'] = $user->id;
            $args['created_by'] = auth()->id();

            $detail = UserDetail::create($args);
            if ($detail)
                return redirect()->back()->withSuccess('Client created successfully!');
            else
                return redirect()->back()->withErrors(['message' => 'Problem while creating client profile. Please try again']);
        } else {
            return redirect()->back()->withErrors(['message' => 'Problem while creating client. Please try again']);
        }
    }

    public function edit($uuid)
    {
        $user = User::with(['profile'])->where('uuid', $uuid)->first();
        return view('clients.edit', compact('user'));
    }

    public function update(Request $request, User $client)
    {
        $rules = [
            'first_name' => 'required|max:255',
            'last_name' => 'required|max:255',
            'company_name' => 'required|max:255',
            'contact_no' => 'required|numeric',
            'email' => 'required|email|max:255|unique:users,email,' . $client->id,
            'address' => 'required'
        ];
        $this->validate($request, $rules, []);

        $client->update(['email' => $request->email]);

        $data = $request->except(['email', 'image']);

        $path = 'avatar-images/' . date('Y') . '/' . date('m');
        $url = '';
        if ($request->file('image')) {
            $uploadedFile = $request->file('image');
            $filename = time() . $uploadedFile->getClientOriginalName();
            Storage::disk('public')->putFileAs($path, $uploadedFile, $filename);
            $url = $path . '/' . $filename;
            $data['image'] = $url;
        }

        $client->profile->update($data);

        return redirect()->back()->withSuccess('Client details updated successfully!');
    }

    public function destroy(User $client)
    {
        $client->profile->delete();
        $client->delete();
        return response()->json(1);
    }

    public function getProjects($uuid)
    {
        $user = User::where('uuid', $uuid)->first();
        return view('clients.projects', compact('user'));
    }

    public function DTProjectData($uuid)
    {
        $client = User::where('uuid', $uuid)->first();
        $projects = Project::where('client_id', $client->id)->leftjoin('users', 'users.id', '=', 'projects.created_by')
            ->leftjoin('user_details', 'user_details.user_id', '=', 'users.id')
            ->select(
                'projects.id',
                'projects.uuid',
                'projects.job_number',
                'projects.job_name',
                'projects.subject',
                'projects.description',
                'projects.location',
                'projects.contact_phone',
                'projects.contact_email',
                'projects.venue_email',
                'projects.created_by',
                'projects.created_at',
                'user_details.first_name',
                'user_details.last_name'
            )->orderby('projects.job_name','ASC');
        return Datatables::of($projects)
            ->addColumn('project_name', function ($project) {
                return '<a href="' . route('projects.edit', $project->uuid) . '">
                    ' . $project->job_name  . '
                </a>';
            })
            ->addColumn('excerpt_desc', function ($project) {
                return str_limit($project->description, 40, '...');
            })
            ->addColumn('creator_name', function ($project) {
                if ($project->createdBy != null) {
                    return '<a href="' . route('staffs.edit', $project->createdBy->uuid) . '">
                    ' . $project->createdBy->profile->first_name . ' ' . $project->createdBy->profile->last_name . '
                </a>';
                } else {
                    return '';
                }
            })
            ->editColumn('created_at', function ($project) {
                return $project->created_at->format('d-m-Y');
            })
            ->rawColumns(['project_name', 'creator_name'])->make(true);
    }
}

avaresearch/app/Http/Controllers/Front/ClientController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User, Auth;


class ClientController extends Controller
{
    public function login()
    {
        return view('front.clients.login');
    }

    public function postLogin(Request $request)
    {
        $this->validate($request, [
            'email'   => 'required|email',
            'password' => 'required'
        ]);

        if (Auth::guard('web')->attempt(['email' => $request->email, 'password' => $request->password, 'type' => 'client'], $request->get('remember'))) {

            return redirect()->intended('/home');
        }

        return redirect()->back()->withErrors(['email' => 'These credentials do not match our records.']);
    }
}

avaresearch/resources/views/clients/create.blade.php
@extends('layouts.app') @section('title', 'Create Client') @section('content')
<div class="container-fluid animatedParent animateOnce my-3 white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">
    <!-- <h4 class="">Fill up the details</h4> -->
    <a href="{{ route('clients.index') }}" class="btn btn-secondary btn-xs"><i class="icon-arrow_back"></i> Back to
      List</a>
    <hr />
    @if(session('success'))
    <div class="toast" data-title="Success" data-message="{{ session("success") }}" data-type="success"></div>
    @endif @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif @if (session('errors'))
    {{ session('errors')->first('message') }}
    @endif
    <form class="form-horizontal" action="{{ route('clients.store') }}" method="POST" enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="first_name" class="control-label">First Name <sup class="mandatory">*</sup> </label>
            <input class="form-control" id="first_name" type="text" name="first_name" value="{{ old('first_name') }}"
              required />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="last_name" class="control-label">Last Name <sup class="mandatory">*</sup></label>
            <input class="form-control" id="first_name" type="text" name="last_name" value="{{ old('last_name') }}"
              required />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="company_name" class="control-label">Company Name <sup class="mandatory">*</sup></label>
            <input class="form-control" id="company_name" type="text" name="company_name"
              value="{{ old('company_name') }}" required />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="website" class="control-label">Website</label>
            <input title="Ex: http://example.com" class="form-control" id="website" type="url" name="website"
              value="{{ old('website') }}" />
            <small class="text-primary">URL must have a protocol http:// or https://</small>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="contact_no" class="control-label">Contact Number <sup class="mandatory">*</sup></label>
            <input class="form-control" id="contact_no" type="text" name="contact_no" value="{{ old('contact_no') }}"
              minlength="10" maxlength="10" onkeypress="return isNumber(event);" required />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="fax_no" class="control-label">Fax Number</label>
            <input class="form-control" id="fax_no" type="text" name="fax_no" value="{{ old('fax_no') }}" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <label for="email" class="control-label">Email Address <sup class="mandatory">*</sup></label>
            <input class="form-control" id="email" type="email" name="email" value="{{ old('email') }}" required />
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label for="password" class="control-label">Password </label>
            <input class="form-control" id="password" type="password" name="password">
             <!-- <small class="text-primary">
              Your password must be between 5 and 10 characters long
            </small>  -->
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label for="password_confirmation" class="control-label">Confirm Password </label>
            <input class="form-control" id="password" type="password" name="password_confirmation" >
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="address" class="control-label">Address <sup class="mandatory">*</sup></label>
            <textarea name="address" id="address" cols="30" rows="10" class="form-control"
              required>{{ old("address") }}</textarea>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="image" class="control-label">Image</label><br />
            <div class="preview-wrap mb-3 hidden"></div>
            <input type="file" name="image" id="image" accept="image/*" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <button class="btn btn-primary"><i class="fa fa-save mr-2"></i>Submit</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

@endsection @section('footer')
<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function(e) {
        $(".preview-wrap")
          .html(`<img src="${e.target.result}" alt="Avatar" class="w-150px" />`)
          .removeClass("hidden");
      };

      reader.readAsDataURL(input.files[0]);
    }
  }
  $("#image").change(function() {
    $(".preview-wrap").addClass("hidden");
    readURL(this);
  });
</script>
@endsection

avaresearch/resources/views/clients/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Client ::'.$user->profile->first_name.' '.$user->profile->last_name)
@section('content')

<div class="row pb-3">
  <div class="col-md-6">
    <a href="{{ route('clients.index') }}" class="btn btn-secondary btn-xs"><i class="icon-arrow_back"></i> Back to
      List</a>
  </div>
</div>

<header class="white pt-2 relative shadow">
  <div class="container-fluid">
    <div class="row">
      <ul class="nav nav-material responsive-tab" id="v-pills-tab" role="tablist">
        <li>
          <a class="nav-link active show" href="javascript:;" role="tab"><i class="icon icon-cog"></i>Details</a>
        </li>
        <li>
          <a class="nav-link" href="{{ route('getProjects', $user->uuid) }}" role="tab"><i
              class="icon icon-briefcase"></i>Jobs</a>
        </li>
      </ul>
    </div>
  </div>
</header>

<div class="container-fluid animatedParent animateOnce white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">

    @if(session('success'))
    <div class="toast" data-title="Success" data-message="{{ session("success") }}" data-type="success"></div>
    @endif

    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif

    @if (session('errors'))
    {{ session('errors')->first('message') }}
    @endif

    <form class="form-horizontal" action="{{ route('clients.update', $user->id) }}" method="POST"
      enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="first_name" class="control-label">First Name <sup class="mandatory">*</sup></label>
            <input class="form-control" id="first_name" type="text" name="first_name"
              value="{{ old('first_name', $user->profile->first_name) }}" required />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="last_name" class="control-label">Last Name <sup class="mandatory">*</sup></label>
            <input class="form-control" id="first_name" type="text" name="last_name"
              value="{{ old('last_name', $user->profile->last_name) }}" required />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="company_name" class="control-label">Company Name <sup class="mandatory">*</sup></label>
            <input class="form-control" id="company_name" type="text" name="company_name"
              value="{{ old('company_name', $user->profile->company_name) }}" required />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="website" class="control-label">Website</label>
            <input class="form-control" id="website" type="url" name="website"
              value="{{ old('website', $user->profile->website) }}" />
            <small class="text-primary">URL must have a protocol http:// or https://</small>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="contact_no" class="control-label">Contact Number <sup class="mandatory">*</sup></label>
            <input class="form-control" id="contact_no" type="text" name="contact_no"
              value="{{ old('contact_no', $user->profile->contact_no) }}" onkeypress="return isNumber(event);"
              required />
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="fax_no" class="control-label">Fax Number</label>
            <input class="form-control" id="fax_no" type="text" name="fax_no"
              value="{{ old('fax_no', $user->profile->fax_no) }}" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="email" class="control-label">Email Address <sup class="mandatory">*</sup></label>
            <input class="form-control" id="email" type="email" name="email" value="{{ old('email', $user->email) }}"
              required />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label for="address" class="control-label">Address <sup class="mandatory">*</sup></label>
            <textarea name="address" id="address" cols="30" rows="10" class="form-control"
              required>{{ old("address", $user->profile->address) }}</textarea>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label for="image" class="control-label">Image</label><br />
            @if($user->profile->image)
            <div class="preview-wrap mb-3">
              <img src="{{ asset('storage/app/public/'.$user->profile->image) }}" class="w-150px" alt="Avatar" />
            </div>
            @else
            <div class="preview-wrap mb-3 hidden"></div>
            @endif
            <input type="file" name="image" id="image" accept="image/*" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <button class="btn btn-primary"><i class="fa fa-save mr-2"></i>Save Changes</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

@section('footer')
<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function(e) {
        $(".preview-wrap")
          .html(`<img src="${e.target.result}" alt="Avatar" class="w-150px" />`)
          .removeClass("hidden");
      };

      reader.readAsDataURL(input.files[0]);
    }
  }
  $("#image").change(function() {
    $(".preview-wrap").addClass("hidden");
    readURL(this);
  });
</script>
@endsection

avaresearch/resources/views/clients/index.blade.php
@extends('layouts.app')
@section('title', 'Clients')
@section('content')
<div class="container-fluid animatedParent animateOnce my-3 white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">
    <!-- <h4 class="">Registered Staffs</h4> -->
    <a href="{{ route('clients.create') }}" class="btn btn-primary btn-xs"><i class="icon-plus"></i> Add New</a>
    <hr />
    @if(session('success'))
    <div class="alert alert-success">{{ session("success") }}</div>
    @endif
    <div class="table-responsive">
      <table class="table table-bordered table-hover" id="clients_table">
        <thead>
          <tr>
            <th>Image</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Contact No</th>
            <th>Address</th>
            <th>Created By</th>
            <th>Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <!-- Data will be placed here -->
          <tr>
            <td colspan="6">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="6">&nbsp;</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection
@section('footer')
<script>
  $(document).ready(function() {
    $("#clients_table").DataTable({
      sDom: "Rlfrtip",
      processing: true,
      serverSide: true,
      pageLength: 10,
      ajax: "{{ route('DTClients') }}",
      columns: [
        { data: "image", name: "user_details.first_name", searchable: false },
        { data: "first_name", name: "user_details.first_name", visible: false },
        { data: "last_name", name: "user_details.last_name", visible: false },
        { data: "contact_no", name: "user_details.contact_no", width: "100px" },
        { data: "address", name: "user_details.address", width: "200px" },
        { data: "created_user_name", name: "users.created_by" },
        { data: "created_at", name: "users.created_at" },
        {
          data: "actions",
          name: "actions",
          orderable: false,
          searchable: false
        }
      ],
      order: [[0, "asc"]]
    });
  });
  $(document).on("click", ".delete_btn", function() {
    var id = $(this).data("id");
    var name = $(this).data("name");
    var row = $(this).closest("tr");
    swal(
      {
        title: "Are you sure to delete",
        text: "Name: " + name,
        type: "warning",
        showCancelButton: true,
        confirmButtonClass: "btn-success",
        confirmButtonText: "Yes",
        cancelButtonText: "No",
        closeOnConfirm: false,
        showLoaderOnConfirm: true
      },
      function(isConfirm) {
        if (isConfirm) {
          $.ajax({
            url: "{{ route('clients.index') }}/" + id,
            type: "DELETE",
            data: { _token: "{{ csrf_token() }}" },
            success: function(res) {
              if (res) {
                row.remove();
                swal("Deleted", "You deleted the client: " + name, "success");
              }
            },
            error: function(err) {
              console.log(err);
            }
          });
        }
      }
    );
  });
</script>
@endsection