avaresearch/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/respondents/login', 'Front\RespondentController@respondentLoginForm')->name('pageRespondentLogin');
Route::post('/respondents/login', 'Front\RespondentController@respondentLogin')->name('respondentLogin');
Route::get('/respondents/register', 'Front\RespondentController@index')->name('register_respondents');
//Demo Responends
Route::get('/respondents/registerdemo', 'Front\RespondentController@indexdemo')->name('register_respondents_demo');

Route::post('/suburb', 'Front\RespondentController@suburb')->name('suburb');
Route::post('/ethnicity', 'Front\RespondentController@ethnicity')->name('ethnicity');
Route::post('/add-respondent', 'Front\RespondentController@store')->name('add-respondent');

Route::get('/respondents/unsubscribe/{uuid}', 'Front\RespondentController@unsubscribe')->name('unsubscribeNow');

Route::post('/respondents/unsubscribe', 'Front\RespondentController@unsubscribeWithReason')->name('unsubscribe-respondent');

Route::get('/respondents/unsubscribeEmail/{uuid}', 'Front\RespondentController@emailUnsubscribe')->name('unsubscribeEmail');


//Route::post('/respondents/unsubscribe', 'Front\RespondentController@postUnsubscribe')->name('unsubscribe-respondent');

Route::post('/respondents/password/email', 'Auth\RespondentForgotPasswordController@sendResetLinkEmail')->name('respondent.password.email');
Route::get('/respondents/password/reset', 'Auth\RespondentForgotPasswordController@showLinkRequestForm')->name('respondent.password.request');
Route::post('/respondents/password/reset', 'Auth\RespondentResetPasswordController@reset')->name('respondent.password.update');
Route::get('/respondents/password/reset/{token}', 'Auth\RespondentResetPasswordController@showResetForm')->name('respondent.password.reset');

Route::get('/clients/login', 'Front\ClientController@login')->name('clientLogin');
Route::post('/clients/login', 'Front\ClientController@postLogin')->name('clientPostLogin');


Route::get('/', function () {
    return redirect(route('home'));
});

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile/edit', 'HomeController@editProfile')->name('edit-profile');
Route::post('/profile/edit', 'HomeController@saveProfile')->name('save-profile');

Route::get('/logout', function () {
    if (auth()->guard('respondent')->check()) {
        //auth('respondent')->user()->update(['login_status' => 0]);
        auth('respondent')->logout();
        return redirect(route('pageRespondentLogin'));
    } else if (auth()->check() && auth()->user()->type == 'client') {
        auth()->user()->update(['login_status' => 0]);
        auth()->logout();
        return redirect(route('clientLogin'));
    } else {
        if (auth()->check()) auth()->user()->update(['login_status' => 0]);
        auth()->logout();
        Session::flush();
        return redirect(route('login'));
    }
})->name('logout');

Route::group(['middleware' => 'auth'], function () {

    Route::resource('staffs', 'StaffController')->middleware('App\Http\Middleware\AdminMiddleware');

    //Clients
    Route::get('/clients/DTData', 'ClientController@DTData')->name('DTClients');
    Route::get('/clients/{uuid}/projects', 'ClientController@getProjects')->name('getProjects');
    Route::get('/clients/{uuid}/DTProjectData', 'ClientController@DTProjectData')->name('DTClientProjects');
    Route::resource('clients', 'ClientController');
    //----------

    //Email Templates
    Route::get('/email-templates/DTData', 'EmailTemplateController@DTData')->name('DTEmailTemplates');
    Route::delete('/email-templates/deleteEmailTempAttach', 'EmailTemplateController@deleteEmailTempAttach')->name('deleteEmailTempAttach');
    Route::get('/email-templates/{template}/json', 'EmailTemplateController@singleJson')->name('EmailTemplateSingleJson');
    Route::resource('email-templates', 'EmailTemplateController');
    //--------------------

    //SMS Templates
    Route::get('/sms-templates/DTData', 'SMSTemplateController@DTData')->name('DTSMSTemplates');
    Route::resource('sms-templates', 'SMSTemplateController');
    //--------------------

    //Calendar
    Route::get('/calendar/DTData', 'CalendarController@DTData')->name('DTCalendar');
    Route::resource('calendar', 'CalendarController');

    //Staff Qualified Report
    Route::post('/staff-qualified-report/getData', 'StaffReportController@getData')->name('getDataDTQualifiedReport');
    Route::resource('staff-qualified-report', 'StaffReportController');

    //Qulified Report
    //Route::resource('/reports', 'QulifiedReportController');

    //Leads
    Route::resource('leads', 'LeadController');

    
});

avaresearch/app/Models/EmailTemplate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class EmailTemplate extends Model
{
    use SoftDeletes;
    protected $guarded = ['uuid'];

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model->uuid = (string) Str::uuid();
        });
    }

    public function attachments()
    {
        return $this->hasMany('App\Models\EmailTemplateAttachment', 'template_id', 'id');
    }

    public function createdBy()
    {
        return $this->belongsTo('App\User', 'created_by', 'id');
    }
}

avaresearch/app/Http/Controllers/EmailTemplateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\EmailTemplate;
use App\Models\EmailTemplateAttachment;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Storage;

class EmailTemplateController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('email_templates.index');
    }

    public function DTData()
    {
        $templates = EmailTemplate::select(
            'email_templates.id',
            'email_templates.uuid',
            'email_templates.title',
            'email_templates.isactive',
            'email_templates.created_by',
            'email_templates.created_at'
        );
        return Datatables::of($templates)
            ->addColumn('template_name', function ($template) {
                return '<a href="' . route('email-templates.edit', $template->uuid) . '">
                    ' . $template->title  . '
                </a>';
            })
            ->addColumn('created_user_name', function ($template) {
                if ($template->createdBy != null) {
                    return '<a href="' . route('staffs.edit', $template->createdBy->uuid) . '">
                    ' . $template->createdBy->profile->first_name . ' ' . $template->createdBy->profile->last_name . '
                </a>';
                } else {
                    return '';
                }
            })
            ->editColumn('created_at', function ($template) {
                return $template->created_at->format('d-m-Y');
            })
            ->addColumn('actions', function ($template) {
                return '<td>
                <a href="' . route('email-templates.edit', $template->uuid) . '"><i class="icon-pencil mr-3"></i></a>
                <a href="javascript:void(0);" class="delete_btn" data-id="' . $template->id . '" data-name="' . $template->title . '"><i class="icon-trash"></i></a>
            </td>';
            })->rawColumns(['template_name', 'actions', 'created_user_name'])->make(true);
    }

    public function create()
    {
        return view('email_templates.create');
    }

    public function store(Request $request)
    {
        $rules = [
            'title' => 'required|max:255',
            'message' => 'required'
        ];
        $this->validate($request, $rules, []);

        //dd($request->all());

        $data = $request->except('attachment');
        $data['created_by'] = auth()->id();

        $template = EmailTemplate::create($data);
        if ($template) {
            if ($request->has('attachment') && count($request->attachment)) {
                $args = [];
                $files = $request->file('attachment');
                if (!empty($files) && count($files)) {
                    $path = 'docs/attachments';
                    foreach ($files as $file) {
                        $filename = time() . $file->getClientOriginalName();
                        Storage::disk('public')->putFileAs($path, $file, $filename);
                        $template->attachments()->create(['template_id' => $template->id, 'url' => $path . '/' . $filename]);
                    }
                }
            }
            return redirect()->back()->withSuccess('Email Template created successfully!');
        } else
            return redirect()->back()->withErrors(['message' => 'Problem while creating email template. Please try again']);
    }

    public function edit($uuid)
    {
        $template = EmailTemplate::where('uuid', $uuid)->first();
        return view('email_templates.edit', compact('template'));
    }

    public function update(Request $request, EmailTemplate $emailTemplate)
    {
        $rules = [
            'title' => 'required|max:255',
            'message' => 'required'
        ];

        $this->validate($request, $rules, []);

        $data = $request->except('attachment');
        $data['modified_by'] = auth()->id();

        $emailTemplate->update($data);

        if ($request->has('attachment') && count($request->attachment)) {
            $emailTemplate->attachments()->delete();
            $args = [];
            $files = $request->file('attachment');
            if (!empty($files) && count($files)) {
                $path = 'docs/attachments';
                foreach ($files as $file) {
                    $filename = time() . str_replace(' ', '-', $file->getClientOriginalName());
                    Storage::disk('public')->putFileAs($path, $file, $filename);
                    $emailTemplate->attachments()->create(['template_id' => $emailTemplate->id, 'url' => $path . '/' . $filename]);
                }
            }
            foreach ($request->attachment as $url) {
                if (is_string($url)) {
                    $emailTemplate->attachments()->create(['template_id' => $emailTemplate->id, 'url' => $url]);
                }
            }
        }
        return redirect()->back()->withSuccess('Email Template updated successfully!');
    }

    public function destroy(EmailTemplate $emailTemplate)
    {
        $emailTemplate->delete();
        return response()->json(1);
    }

    public function deleteEmailTempAttach(Request $request)
    {
        $attch = EmailTemplateAttachment::find($request->id);
        if ($attch != null) {
            unlink(storage_path('app/public/' . $attch->url));
            $attch->delete();
        }
        return response()->json(1);
    }

    public function singleJson(EmailTemplate $template)
    {
        $template = EmailTemplate::with(['attachments'])->find($template->id);
        return response()->json($template);
    }
}

avaresearch/app/Http/Controllers/Project/Group/ProjectGroupAllRespondentController.php
<?php

namespace App\Http\Controllers\Project\Group;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;

use App\Models\Project;
use App\Models\ProjectGroup;
use App\Models\Respondents\Respondent;
use App\Models\Project\JobEvent;

class ProjectGroupAllRespondentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($projectUUID, $groupUuid)
    {
        $project = Project::where('uuid', $projectUUID)->first();
        $group = ProjectGroup::where('uuid', $groupUuid)->first();
        return view('projects.groups.all-respondents', compact('project', 'group'));
    }

    public function DTAllRespondents($projectUuid, $groupUuid)
    {
        $group = ProjectGroup::where('uuid', $groupUuid)->first();
        $respondents = JobEvent::where('group_id', $group->id)->whereIn('job_events.name', ['Screened OK', 'Qualified', 'Screened OK – Quotas Full'])
            ->leftjoin('respondents', 'respondents.id', '=', 'job_events.respondent_id')
            ->selectRaw(
                'job_events.id, job_events.respondent_id, CONCAT(respondents.first_name," ",respondents.last_name) as name, 
                respondents.last_name'
            );
        return Datatables::of($respondents)
            ->addColumn('check_row', function ($query) {
                $respondent = Respondent::find($query->respondent_id);
                $email = '';
                $mobile = '';
                if ($respondent != null) {
                    $email = ($respondent->email && $respondent->stop_often_email != 1) ? $respondent->email : '';
                    $mobile = ($respondent->detail->mobile_phone && $respondent->wrong_number != 1) ? $respondent->detail->mobile_phone : '';
                }
                return '<td><input type="checkbox" name="row_check" class="row_check" value="' . $query->id . '" data-email="' . $email . '" 
                data-mobile="' . $mobile . '" /></td>';
            })
            ->addColumn('actions', function ($query) {
                return '<td>
                            <a href="javascript:void(0);" class="btn btn-outline-primary btn-xs reverse_btn" data-id="' . $query->id . '" data-name="' . $query->name . '">
                                <i class="icon-trash"></i> Reverse Job qualified 
                            </a>
                        </td>';
            })->rawColumns(['check_row', 'actions'])->make(true);
    }

    public function reverse(Request $request, $projectUuid, $groupUuid)
    {
        $id = $request->id;
        $job_event = JobEvent::find($id);
        if ($job_event != null) $job_event->delete();
        return response()->json(1);
    }
}

avaresearch/app/Http/Controllers/Project/Group/ProjectGroupStandByRespondentController.php
<?php

namespace App\Http\Controllers\Project\Group;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\Datatables\Datatables;

use App\Models\Project;
use App\Models\ProjectGroup;
use App\Models\Project\JobEvent;

class ProjectGroupStandByRespondentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($projectUuid, $groupUuid)
    {
        $group = ProjectGroup::where('uuid', $groupUuid)->first();
        return view('projects.groups.standby-respondents', compact('group'));
    }

    public function DTStandByRespondents($projectUuid, $groupUuid)
    {
        $group = ProjectGroup::where('uuid', $groupUuid)->first();
        $respondents = JobEvent::where('group_id', $group->id)->where('job_events.name', 'Standby')
            ->leftjoin('respondents', 'respondents.id', '=', 'job_events.respondent_id')
            ->selectRaw(
                'job_events.id, job_events.respondent_id, CONCAT(respondents.first_name," ",respondents.last_name) as name, 
                respondents.last_name'
            );
        return Datatables::of($respondents)
            ->addColumn('check_row', function ($query) {
                return '<td><input type="checkbox" name="check_row" value="' . $query->id . '" /></td>';
            })
            ->addColumn('actions', function ($query) {
                return '<td>
                            <a href="javascript:void(0);" class="btn btn-outline-primary btn-xs reverse_btn" data-id="' . $query->id . '" data-name="' . $query->name . '">
                                <i class="icon-trash"></i> Reverse Job qualified 
                            </a>
                        </td>';
            })->rawColumns(['check_row', 'actions'])->make(true);
    }

    public function move(Request $request, $projectUuid, $groupUuid)
    {
        $ids = $request->ids;
        $res = JobEvent::whereIn('id', $ids)->update(['name' => 'Screened OK']);
        return response()->json($res, 200);
    }

    public function reverse(Request $request, $projectUuid, $groupUuid)
    {
        $id = $request->id;
        $job_event = JobEvent::find($id);
        if ($job_event != null) $job_event->delete();
        return response()->json(1);
    }
}

avaresearch/resources/views/projects/groups/email_templates/create.blade.php
@extends('layouts.app')
@section('title', 'Create Email Template :: '.$group->name.' | '.$project->job_name.' (#'.$project->job_number.')')
@section('content')

@include('projects.tab-nav', ['project' => $project,'current'=>'create_group_email_template', 'group' => $group])

<div class="container-fluid animatedParent animateOnce my-3 white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">
    @if(session('success'))
    <div class="toast" data-title="Success" data-message="{{ session("success") }}" data-type="success"></div>
    @endif

    @if ($errors->any())
    <div class="alert alert-danger">
      <ul class="mb-0">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif

    <form class="form-horizontal" action="{{ route('storeProjectGroupEmailTemp', [$project->uuid, $group->uuid]) }}"
      method="POST" enctype="multipart/form-data">
      @csrf
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="master_template" class="control-label">Email Template</label>
            <select name="master_template" id="master_template" class="form-control select2">
              <option value="">Select Template</option>
              @foreach ($templates as $template)
              <option value="{{ $template->id }}">{{ $template->title }}</option>
              @endforeach
            </select>
          </div>
          <i class="fa fa-spinner fa-spin loading" style="display:none;"></i>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="title" class="control-label">Title <sup class="mandatory">*</sup></label>
            <input class="form-control" id="title" type="text" name="title" value="{{ old('title') }}" required />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="message" class="control-label">Message <sup class="mandatory">*</sup></label>
            <textarea name="message" id="message" rows="10" class="form-control"
              required>{{ old('message') }}</textarea>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="attachments" class="control-label">Attachments</label><br />
            <input type="file" class="attach_file" name="attachment[]" data-id="1" /><br />
            <div class="attach_data attach_data_1"><br /></div>
            <input type="file" class="attach_file" name="attachment[]" data-id="2" /><br />
            <div class="attach_data attach_data_2"><br /></div>
            <input type="file" class="attach_file" name="attachment[]" data-id="3" />
            <div class="attach_data attach_data_3"><br /></div>

            <input type="hidden" id="attachment_1" name="t_attachment[]" value="" />
            <input type="hidden" id="attachment_2" name="t_attachment[]" value="" />
            <input type="hidden" id="attachment_3" name="t_attachment[]" value="" />

          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <button class="btn btn-primary"><i class="fa fa-save mr-2"></i>Submit</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
@endsection

@section('footer')
<script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>
<script>
  CKEDITOR.replace( 'message' );
  $('#master_template').change(function(){
    var id = $(this).val();
    $.ajax({
      url: "{{ route('email-templates.index') }}"+'/'+id+'/json',
      dataType: 'json',
      beforeSend: function(){
        $('.loading').show();
      },
      success: function(res){
        $('#title').val(res.title);
        CKEDITOR.instances.message.setData(res.message);
        if(res.attachments.length){
          for(var i = 0; i < res.attachments.length; i++){
            $('.attach_data_'+(i+1)).html('<a href="{{ asset("storage/app/public") }}/'+res.attachments[i].url+'">'+res.attachments[i].url.split('/').reverse()[0]+'</a>&nbsp;&nbsp;<a href="javascript:void(0);" class="_remove_attach"><i class="icon-times"></i></a><br />');
            $('#attachment_'+(i+1)).val(res.attachments[i].url);
          }
        } else {
          for(var i = 0; i < 3; i++){
            $('.attach_data_'+(i+1)).html('');
            $('#attachment_'+(i+1)).val('');
          }
        }
      },
      error: function(err){
        console.log(err);
        alert(err.responseText);
      },
      complete: function(){
        $('.loading').hide();
      }
    });
  });
  $(document).on('click', '._remove_attach', function(){
    $(this).closest('.attach_data').html('<br/>');
  });
  $('.attach_file').change(function(){
    var id = $(this).data('id');
    $('.attach_data_'+id).html('<br/>');
    $('#attachment_'+id).val('');
  });
</script>
@endsection

avaresearch/resources/views/projects/groups/email_templates/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit Email Template :: '.$template->title. ' | ' .$group->name.' | '.$project->job_name.'
(#'.$project->job_number.')')
@section('content')

@include('projects.tab-nav', ['project' => $project,'current'=>'email_templates', 'group' => $group])

<div class="container-fluid animatedParent animateOnce my-3 white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">

    @if(session('success'))
    <div class="toast" data-title="Success" data-message="{{ session("success") }}" data-type="success"></div>
    @endif

    @if ($errors->any())
    <div class="alert alert-danger">
      <ul class="mb-0">
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif

    <form class="form-horizontal"
      action="{{ route('updateProjectGroupEmailTemp', [$project->uuid,$group->uuid,$template->id]) }}" method="POST"
      enctype="multipart/form-data">
      @csrf
      @method('PUT')
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="title" class="control-label">Title <sup class="mandatory">*</sup></label>
            <input class="form-control" id="title" type="text" name="title" value="{{ old('title',$template->title) }}"
              required />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="message" class="control-label">Message <sup class="mandatory">*</sup></label>
            <textarea name="message" id="message" rows="10" class="form-control"
              required>{{ old('message',$template->message) }}</textarea>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label for="attachments" class="control-label">Attachments</label><br />
            <input type="file" name="attachment[]" /><br />
            @if($template->attachments != null && isset($template->attachments[0]))
            <div class="attach_wrap">
              <br />
              <a href="{{ asset('storage/app/public/'.$template->attachments[0]->url) }}"
                target="_blank">{{ basename($template->attachments[0]->url) }}</a>
              <a href="javascript:void(0);" class="remove_attach" data-attach="{{ $template->attachments[0]->id }}"
                data-name="{{basename($template->attachments[0]->url)  }}"><i class="icon-times"></i></a>
              <input type="hidden" name="attachment[]" value="{{ $template->attachments[0]->url }}" />
              <br />
            </div>
            @endif
          </div>
          <div class="form-group">
            <input type="file" name="attachment[]" /><br />
            @if($template->attachments != null && isset($template->attachments[1]))
            <div class="attach_wrap">
              <br />
              <a href="{{ asset('storage/app/public/'.$template->attachments[1]->url) }}"
                target="_blank">{{ basename($template->attachments[1]->url) }}</a>
              <a href="javascript:void(0);" class="remove_attach" data-attach="{{ $template->attachments[1]->id }}"
                data-name="{{basename($template->attachments[1]->url)  }}"><i class="icon-times"></i></a>
              <input type="hidden" name="attachment[]" value="{{ $template->attachments[1]->url }}" />
              <br />
            </div>
            @endif
          </div>
          <div class="form-group">
            <input type="file" name="attachment[]" />
            @if($template->attachments != null && isset($template->attachments[2]))
            <div class="attach_wrap">
              <br />
              <a href="{{ asset('storage/app/public/'.$template->attachments[2]->url) }}"
                target="_blank">{{ basename($template->attachments[2]->url) }}</a>
              <a href="javascript:void(0);" class="remove_attach" data-attach="{{ $template->attachments[2]->id }}"
                data-name="{{basename($template->attachments[2]->url)  }}"><i class="icon-times"></i></a>
              <input type="hidden" name="attachment[]" value="{{ $template->attachments[2]->url }}" />
              <br />
            </div>
            @endif
          </div>
        </div>
      </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <button class="btn btn-primary"><i class="fa fa-save mr-2"></i>Save Changes</button>
      </div>
    </div>
  </div>
  </form>
</div>
</div>
@endsection

@section('footer')
<script src="https://cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>
<script>
  CKEDITOR.replace( 'message' );

  jQuery('.remove_attach').click(function(){
    var btn = jQuery(this);
    var id = btn.data('attach');
    var name = btn.data('name');
    swal(
      {
        title: "Are you sure to delete",
        text: "Name: " + name,
        type: "warning",
        showCancelButton: true,
        confirmButtonClass: "btn-success",
        confirmButtonText: "Yes",
        cancelButtonText: "No",
        closeOnConfirm: false,
        showLoaderOnConfirm: true
      },
      function(isConfirm) {
        if (isConfirm) {
          $.ajax({
            url: "{{ route('deleteEmailTempAttach') }}",
            type: "DELETE",
            data: { _token: "{{ csrf_token() }}", id: id },
            success: function(res) {
              if (res) {
                btn.closest('.attach_wrap').remove();
                swal("Deleted", "You deleted the attachment", "success");
              }
            },
            error: function(err) {
              console.log(err);
            }
          });
        }
      }
    );
  });
</script>
@endsection

avaresearch/resources/views/projects/groups/email_templates/index.blade.php
@extends('layouts.app')
@section('title', 'Email Templates :: '.$group->name.' | '.$project->job_name.' (#'.$project->job_number.')')
@section('content')

@include('projects.tab-nav', ['project' => $project,'current'=>'group_email_templates', 'group' => $group])

<div class="container-fluid animatedParent animateOnce my-3 white relative shadow pt-3 pb-3">
  <div class="animated fadeInUpShort go">
    <div class="row pb-2">
      <div class="col pl-4">
        <a href="{{ route('createProjectGroupEmailTemp', [$project->uuid, $group->uuid]) }}"
          class="btn btn-primary btn-xs"><i class="icon-plus"></i> Create
          Template</a>
      </div>
    </div>

    <div class="table-responsive">
      <table class="table table-bordered table-hover" id="list_table">
        <thead>
          <tr>
            <th>Serial No</th>
            <th visible="hide">Title</th>
            <th>Title</th>
            <th>Created By</th>
            <th>Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <!-- Data will be placed here -->
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
          <tr>
            <td colspan="5">&nbsp;</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection
@section('footer')
<script>
  $(document).ready(function() {
      $("#list_table").DataTable({
        sDom: "Rlfrtip",
        processing: true,
        serverSide: true,
        pageLength: 10,
        ajax: "{{ route('DTPGEmailTemps', [$project->uuid,$group->uuid]) }}",
        columns: [
          {
            "title": "Serial",
            render: function (data, type, row, meta) {
              return meta.row + meta.settings._iDisplayStart + 1;
            },
            width: '2%'
          },
          { data: 'title', name: 'title', visible: false },
          { data: 'template_name', name: 'title'},
          { data: 'creator_name', name: 'created_by'},
          { data: 'created_at', name: 'created_at'},
          {
            data: "actions",
            name: "actions",
            orderable: false,
            searchable: false
          }
        ],
        order: [[0, "asc"]]
      });
    });
    $(document).on("click", ".delete_btn", function() {
      var id = $(this).data("id");
      var name = $(this).data("name");
      var row = $(this).closest("tr");
      swal(
        {
          title: "Are you sure to delete",
          text: "Name: " + name,
          type: "warning",
          showCancelButton: true,
          confirmButtonClass: "btn-success",
          confirmButtonText: "Yes",
          cancelButtonText: "No",
          closeOnConfirm: false,
          showLoaderOnConfirm: true
        },
        function(isConfirm) {
          if (isConfirm) {
            $.ajax({
              url: "{{ route('indexProjectGroupEmailTemp', [$project->uuid, $group->uuid]) }}/" + id,
              type: "DELETE",
              data: { _token: "{{ csrf_token() }}" },
              success: function(res) {
                if (res) {
                  row.remove();
                  swal("Deleted", "You deleted the template: " + name, "success");
                }
              },
              error: function(err) {
                console.log(err);
              }
            });
          }
        }
      );
    });
</script>
@endsection